version: '3.8'

services:
  curriculum:
    container_name: curriculum
    image: curriculum-image
    build:
      context: .
    volumes:
      - '.:/app'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
